server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: reviews

ratings:
  enabled: true
  server-addr: http://ratings
  color: red

management:
  endpoints:
    web:
      exposure:
        include: "*"