server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: spring-boot-admin
  cloud:
    kubernetes:
      discovery:
        all-namespaces: false
        include-not-ready-addresses: false