server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: spring-boot-admin
  cloud:
    consul:
      host: consul-application-consul-server.consul-demo.svc # 填对应 consul 地址
      port: 8500 # consul 默认端口
      discovery:
        prefer-ip-address: true # springcloud 中使用 consul 注册服务时默认使用的 hostname ，需要换成IP
